config/routes.rb
Rails.application.routes.draw do
  resources :scores
  resources :students
  resources :users
  get 'main/login'
 post 'main/create'
  get 'main/destroy'
  get 'students/:id/edit_score',to:'students#edit_score'
  # post 'studemt/:'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
	has_many:score ,dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :my_debug
	def my_debug
		pp '------------'
		pp session.to_h
	end

	private 
		def is_login?
			return	session[:logged_in]==true
		end
		def must_be_logged_in
			if is_login?
				return true
			else
				redirect_to main_login_path, notice: 'you must login before access this page'
			end
		end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def login
  end

  def create
    u=User.where(login: params[:login]).first
    if u&&u.authenticate(params[:password])
      redirect_to students_path
      session[:logged_in]=true
    else
      redirect_to main_login_path
    end
  end

  def destroy
    reset_session
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :must_be_logged_in
  before_action :set_score, only: %i[ show edit update destroy ]

  # GET /scores or /scores.json
  def index
    @scores = Score.all
  end

  # GET /scores/1 or /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores or /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to score_url(@score), notice: "Score was successfully created." }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1 or /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to score_url(@score), notice: "Score was successfully updated." }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1 or /scores/1.json
  def destroy
    @score.destroy

    respond_to do |format|
      format.html { redirect_to scores_url, notice: "Score was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def score_params
      params.require(:score).permit(:student_id, :subject, :point, :grade)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # before_action :must_be_logged_in
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
    must_be_logged_in
  end

  # GET /students/new
  def new
    must_be_logged_in
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
    must_be_logged_in
  end

  # POST /students or /students.json
  def create
    must_be_logged_in
    @student = Student.new(student_params)
    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    must_be_logged_in
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    must_be_logged_in
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def edit_score
      @student = Student.find(params[:id])
      sum = 0
      cnt = 0
      mx = -1
      @mxsub = ""
      for score in Score.where(student: @student)
        sum += score.point
        cnt+=1
        if score.point > mx
          mx = score.point
          @mxsub = score.subject
        end
      end
      if cnt==0
        @avg=0
      else
      @avg = sum/cnt
      end
      @db = Score.where(student: @student)
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :dob, :student_no, :class_year)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :must_be_logged_in
  # before_action :set_user, only: %i[ show edit update destroy ]

  # # GET /users or /users.json
  # def index
  #   @users = User.all
  # end

  # # GET /users/1 or /users/1.json
  # def show
  # end

  # # GET /users/new
  # def new
  #   @user = User.new
  # end

  # # GET /users/1/edit
  # def edit
  # end

  # # POST /users or /users.json
  # def create
  #   @user = User.new(user_params)

  #   respond_to do |format|
  #     if @user.save
  #       format.html { redirect_to user_url(@user), notice: "User was successfully created." }
  #       format.json { render :show, status: :created, location: @user }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /users/1 or /users/1.json
  # def update
  #   respond_to do |format|
  #     if @user.update(user_params)
  #       format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
  #       format.json { render :show, status: :ok, location: @user }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /users/1 or /users/1.json
  # def destroy
  #   @user.destroy

  #   respond_to do |format|
  #     format.html { redirect_to users_url, notice: "User was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_user
  #     @user = User.find(params[:id])
  #   end

  #   # Only allow a list of trusted parameters through.
  #   def user_params
  #     params.require(:user).permit(:login, :full_name, :admin)
  #   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lec08</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="
sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class='container'>
    <% flash.each do |type,msg|%>
      <p>
        <%=msg%>
      <p>
    <%end%>
    <%= yield %>
  </div>
  </body>
</html>

app/views/main/create.html.erb
<h1>Main#create</h1>
<p>Find me in app/views/main/create.html.erb</p>

app/views/main/destroy.html.erb
<h1>Main#destroy</h1>
<p>Find me in app/views/main/destroy.html.erb</p>

app/views/main/login.html.erb
<%="Main#login"%>
<%= form_with url: main_create_path,data: {turbo: false} do |form| %>
  <%= form.label :login, class: "form-label"%>
  <%=form.text_field :login, class: "form-control"%>
   <br/>
  <%= form.label :password, class: "form-label"%>
  <%=form.password_field :password , class: "form-control"%>
 <br/>
 
  <%=form.submit :OK,class: "btn btn-secondary"%>
<% end %>

app/views/scores/_form.html.erb
<%= form_with(model: score) do |form| %>
  <% if score.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
        <% score.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :student_id, style: "display: block" ,class: "form-label"%>
    <%= form.text_field :student_id ,class: "form-control"%>
  </div>

  <div>
    <%= form.label :subject, style: "display: block" ,class: "form-label"%>
    <%= form.text_field :subject ,class: "form-control"%>
  </div>

  <div>
    <%= form.label :point, style: "display: block" ,class: "form-label"%>
    <%= form.number_field :point ,class: "form-control"%>
  </div>

  <div>
    <%= form.label :grade, style: "display: block" ,class: "form-label"%>
    <%= form.text_field :grade ,class: "form-control"%>
  </div>

  <div>
    <%= form.submit class: "mr-1 mt-2 col-5 btn btn-secondary"%>
  </div>
<% end %>

app/views/scores/_score.html.erb
<div id="<%= dom_id score %>">
  <p>
    <strong>Student:</strong>
    <%= score.student_id %>
  </p>

  <p>
    <strong>Subject:</strong>
    <%= score.subject %>
  </p>

  <p>
    <strong>Point:</strong>
    <%= score.point %>
  </p>

  <p>
    <strong>Grade:</strong>
    <%= score.grade %>
  </p>

</div>

app/views/scores/edit.html.erb
<h1>Editing score</h1>

<%= render "form", score: @score %>

<br>

<div>
  <%= link_to "Show this score", @score ,class: "mr-1 col-5 btn btn-secondary "%> 
  <%= link_to "Back to scores", scores_path ,class: "mr-1 col-5 btn btn-secondary "%>
</div>

app/views/scores/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Scores</h1>

<div id="scores">
  <% @scores.each do |score| %>
    <%= render score %>
    <p>
      <%= link_to "Show this score", score ,class: "btn btn-secondary"%>
    </p>
  <% end %>
</div>

<%= link_to "New score", new_score_path ,class: "btn btn-secondary"%>

app/views/scores/new.html.erb
<h1>New score</h1>

<%= render "form", score: @score %>

<br>

<div>
  <%= link_to "Back to scores", scores_path ,class: "btn btn-secondary"%>
</div>

app/views/scores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @score %>

<div>
  <%= link_to "Edit this score", edit_score_path(@score) ,class: "mr-1 col-5 btn btn-secondary "%> 
  <%= link_to "Back to scores", scores_path ,class: "col-5 btn btn-secondary"%>

  <%= button_to "Destroy this score", @score, method: :delete ,class: "mt-1 col-5 btn btn-secondary"%>
</div>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" ,class: "form-label"%>
    <%= form.text_field :name ,class: "form-control"%>
  </div>

  <div>
    <%= form.label :dob, style: "display: block" ,class: "form-label"%>
    <%= form.date_field :dob ,class: "form-control"%>
  </div>

  <div>
    <%= form.label :student_no, style: "display: block" ,class: "form-label"%>
    <%= form.text_field :student_no ,class: "form-control"%>
  </div>

  <div>
    <%= form.label :class_year, style: "display: block" ,class: "form-label"%>
    <%= form.number_field :class_year ,class: "form-control"%>
  </div>

  <div>
    <%= form.submit class: "mr-1 mt-2 col-5 btn btn-secondary" %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p>

  <p>
    <strong>Dob:</strong>
    <%= student.dob %>
  </p>

  <p>
    <strong>Student no:</strong>
    <%= student.student_no %>
  </p>

  <p>
    <strong>Class year:</strong>
    <%= student.class_year %>
  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student ,class: "mr-1 col-5 btn btn-secondary "%> 
  <%= link_to "Back to students", students_path ,class: "mr-1 col-5 btn btn-secondary "%>
</div>

app/views/students/edit_score.html.erb
<!--   <style>
    table, th, td {
      border: 1px solid black;
      border-collapse: collapse;
      border-color: blueviolet;
    }
    th, td {
      padding: 15px;
    }
  </style> -->
  <%= @temp %>

    <table class="table">
      <tr class="table-primary">
        <th ></th>
        <th >Subject</th>
        <th >Score</th>
        <%if session[:logged_in]%>
        <th ></th>
        <th ></th>
        <% end %>
      </tr >
      <% i = 1 %>
      <% for data in @db %>
        <tr class="table-info">
          <td ><%= i %></td>
          <td ><%= data.subject %></td>
          <td ><%= data.point %></td>
           <%if session[:logged_in]%>
      <%= form_with url:edit_score_path(data.id), data: {turbo:false}, method: :get do |form| %>
          <td ><%= form.submit "edit", name:"edit#{i}",class: "btn btn-secondary" %></td>
          <%end%>
           <%= form_with url:score_path(data.id), data: {turbo:false}, method: "delete" do |form| %>
          <td ><%= form.submit "delete", name:"delete#{i}" ,class: "btn btn-secondary"%></td>
          <%end%>
        <%end%>
          <% i+=1 %>
        </tr>
      <% end %>
    </table>
    Average = <%= @avg %>
    <br>
    Max subject is <%= @mxsub %>
    <%= form_with url:new_score_path, data: {turbo:false}, method: :get do |form| %>
    <%if session[:logged_in]%>
      <%= form.submit "new score" ,class: "btn btn-secondary"%>
  <%end%>
      <%end%>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<div id="students">
  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%if session[:logged_in]%>
      <%= link_to "Show this student", student ,class: "btn btn-secondary"%>
      <%end%>
    </p>
  <% end %>
</div>
<%if session[:logged_in]%>
      <%= link_to "New student", new_student_path,class: "btn btn-secondary" %>
  <%end%>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path ,class: "btn btn-secondary"%>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) ,class: "mr-1 col-5 btn btn-secondary "%> 
  <%= link_to "Back to students", students_path,class: "col-5 btn btn-secondary" %>

  <%= button_to "Destroy this student", @student, method: :delete ,class: "mt-1 col-5 btn btn-secondary"%>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :login, style: "display: block" %>
    <%= form.text_field :login %>
  </div>

  <div>
    <%= form.label :full_name, style: "display: block" %>
    <%= form.text_field :full_name %>
  </div>

  <div>
    <%= form.label :admin, style: "display: block" %>
    <%= form.check_box :admin %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Login:</strong>
    <%= user.login %>
  </p>

  <p>
    <strong>Full name:</strong>
    <%= user.full_name %>
  </p>

  <p>
    <strong>Admin:</strong>
    <%= user.admin %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>